name: McBank
main: cz.MilanT.mcbank.Main
version: 1.0
softdepend: [Vault]
author: MilanT
commands:
  adminbank:
    usage: /<command>
    description: Administration of server economy
  mcbank:
    usage: /<command>
    description: Administration of your bank account